routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'EmployeeController@index');

Route::resource('employee', 'EmployeeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model {
	protected $fillable = [
		'name',
		'address_line_1',
		'address_line_2',
		'location',
		'zip_code',
		'postal_area',
		'taluka',
		'suburb',
		'direction',
		'city',
		'distict',
		'state',
		'country',
	];

	public function mobile() {
		return $this->hasMany(EmployeeMobile::class, 'employee_id');
	}

	public function whatsapp() {
		return $this->hasMany(EmployeeWhatsapp::class, 'employee_id');
	}

	public function email() {
		return $this->hasMany(EmployeeEmail::class, 'employee_id');
	}
}

app/EmployeeEmail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeEmail extends Model {
	protected $fillable = [
		'employee_id',
		'email',
		'is_primary',
	];
}

app/EmployeeMobile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeMobile extends Model {
	protected $fillable = [
		'employee_id',
		'mobile',
		'is_primary',
	];
}

app/EmployeeWhatsapp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeWhatsapp extends Model {
	protected $fillable = [
		'employee_id',
		'whatsapp_mobile',
		'is_primary',
	];
}

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\EmployeeEmail;
use App\EmployeeMobile;
use App\EmployeeWhatsapp;
use App\State;
use Illuminate\Http\Request;

class EmployeeController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$employees = Employee::all();
		return view('employee.index', compact('employees'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		$states = State::all();
		return view('employee.create', compact('states'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$this->validate($request, [
			'name' => 'required',
			'address_line_1' => 'required',
			'city' => 'required',
		]);

		$employee = Employee::create($request->all());

		foreach ($request->mobile as $key => $value) {
			if ($value != null) {
				EmployeeMobile::create([
					'employee_id' => $employee->id,
					'mobile' => $value,
				]);
			}
		}

		foreach ($request->email as $key => $value) {
			if ($value != null) {
				EmployeeEmail::create([
					'employee_id' => $employee->id,
					'email' => $value,
				]);
			}
		}

		foreach ($request->whatsapp_mobile as $key => $value) {
			if ($value != null) {
				EmployeeWhatsapp::create([
					'employee_id' => $employee->id,
					'whatsapp_mobile' => $value,
				]);
			}
		}

		return redirect()->route('employee.index')->with('success', 'Employee added successfully');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  \App\Employee  $employee
	 * @return \Illuminate\Http\Response
	 */
	public function show(Employee $employee) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Employee  $employee
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Employee $employee) {
		$states = State::all();
		return view('employee.edit', compact('states', 'employee'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \App\Employee  $employee
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Employee $employee) {
		$this->validate($request, [
			'name' => 'required',
			'address_line_1' => 'required',
			'city' => 'required',
		]);

		$employee->update($request->all());

		$mobile_id_array = array();
		$email_id_array = array();
		$whatsapp_mobile_id_array = array();

		$old_mobile_ids = $employee->mobile()->pluck('id')->toArray();
		$old_whatsapp_ids = $employee->whatsapp()->pluck('id')->toArray();
		$old_email_ids = $employee->email()->pluck('id')->toArray();

		if (count($request->mobile) > 0) {
			foreach ($request->mobile as $key => $value) {
				if ($value != null) {
					if ($request->mobile_id[$key] == null) {
						EmployeeMobile::create([
							'employee_id' => $employee->id,
							'mobile' => $value,
						]);
					} else {
						EmployeeMobile::where('id', $request->mobile_id[$key])->update([
							'mobile' => $value,
						]);
						array_push($mobile_id_array, $request->mobile_id[$key]);
					}
				}
			}
		}

		foreach ($request->email as $key => $value) {
			if ($value != null) {
				if ($request->email_id[$key] == null) {
					EmployeeEmail::create([
						'employee_id' => $employee->id,
						'email' => $value,
					]);
				} else {
					EmployeeEmail::where('id', $request->email_id[$key])->update([
						'email' => $value,
					]);
					array_push($email_id_array, $request->email_id[$key]);
				}
			}
		}

		foreach ($request->whatsapp_mobile as $key => $value) {
			if ($value != null) {
				if ($request->whatsapp_mobile_id[$key] == null) {
					EmployeeWhatsapp::create([
						'employee_id' => $employee->id,
						'whatsapp_mobile' => $value,
					]);
				} else {
					EmployeeWhatsapp::where('id', $request->whatsapp_mobile_id[$key])->update([
						'whatsapp_mobile' => $value,
					]);
					array_push($whatsapp_mobile_id_array, $request->whatsapp_mobile_id[$key]);
				}
			}
		}

		foreach ($old_mobile_ids as $key => $value) {
			if (!in_array($value, $mobile_id_array)) {
				EmployeeMobile::where('id', $value)->delete();
			}
		}

		foreach ($old_whatsapp_ids as $key => $value) {
			if (!in_array($value, $whatsapp_mobile_id_array)) {
				EmployeeWhatsapp::where('id', $value)->delete();
			}
		}

		foreach ($old_email_ids as $key => $value) {
			if (!in_array($value, $email_id_array)) {
				EmployeeEmail::where('id', $value)->delete();
			}
		}

		return redirect()->route('employee.index')->with('success', 'Employee updated successfully');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \App\Employee  $employee
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Employee $employee) {
		$employee->mobile()->delete();
		$employee->whatsapp()->delete();
		$employee->email()->delete();
		$employee->delete();

		return ['success'];
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.master')

@section('page-content')
	<div class="container">
		<form action="{{ route('employee.store') }}" method="post">
			@csrf
			<div class="row">
				<div class="col-md-12">
					<h2>Employee Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label>Employee Name<sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="name" id="name" class="form-control" required="" placeholder="Enter Name" value="{{old('name')}}">
						@error('name')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h2>Address Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label>Address 1<sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="address_line_1" id="address_line_1" class="form-control"  required="" placeholder="Enter Address 1" value="{{old('address_line_1')}}">
						@error('address_line_1')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Address 2</label>
						<input type="text" name="address_line_2" id="address_line_2" class="form-control"  placeholder="Enter Address 2" value="{{old('address_line_2')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Location</label>
						<input type="text" name="location" id="location" class="form-control"  placeholder="Enter Address 2" value="{{old('location')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Zip/Pincode</label>
						<input type="text" name="zip_code" id="zip_code" class="form-control"  placeholder="Enter Zip/Pincode" value="{{old('zip_code')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Postal Area</label>
						<input type="text" name="postal_area" id="postal_area" class="form-control"  placeholder="Enter Postal Area" value="{{old('postal_area')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Taluka</label>
						<input type="text" name="taluka" id="taluka" class="form-control"  placeholder="Enter Taluka" value="{{old('taluka')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Suburb</label>
						<input type="text" name="suburb" id="suburb" class="form-control"  placeholder="Enter Taluka" value="{{old('suburb')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>East/West</label>
						<input type="text" name="direction" id="direction" class="form-control"  placeholder="Enter East/West" value="{{old('direction')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>City <sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="city" id="city" class="form-control" required="" placeholder="Enter East/West"value="{{old('city')}}">
						@error('city')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Distict</label>
						<input type="text" name="distict" id="distict" class="form-control"  placeholder="Enter Distict"value="{{old('distict')}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>State</label>
						<select class="form-control" name="state" id="state">
							<option value="">-- Select State --</option>
							@foreach($states as $state)
								<option value="{{$state->state_name}}" @if($state->state_name == 'MAHARASHTRA') selected @endif>{{$state->state_name}}</option>
							@endforeach
						</select>
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>County</label>
						<select class="form-control" name="country" id="country">
							<option value="">-- Select Country --</option>
							<option value="India" selected="">India</option>
							<option value="USA">USA</option>
							<option value="UK">UK</option>
							<option value="Shri Lanka">Shri Lanka</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h2>Contact Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_mobile" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Mobile Numbers </label>
						</div>
						<div class="form-group">
							<label>
								Mobile
							</label>
							<!-- <label style="float:right;text-align:right"><input type="radio" name="primary_mobile[]" checked=""> Primary?</label> -->
							<input type="text" name="mobile[]" class="form-control"  placeholder="Enter Mobile number">
						</div>
						<div id="append_mobile"></div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_whatsapp" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Whatsapp Numbers</label>
						</div>
						<div class="form-group">
							<!-- <label style="float:right;text-align:right">
								<input type="radio" name="primary_whatsapp[]"  checked=""> Primary?
							</label> -->
							<label>Whatsapp Number</label>
							<input type="text" name="whatsapp_mobile[]" class="form-control"  placeholder="Enter Whatsapp number">
						</div>
						<div id="append_whatsapp"></div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_email" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Email Addresses</label>
						</div>
						<div class="form-group">
							<!-- <label style="float:right;text-align:right">
								<input type="radio" name="primary_email[]" checked=""> Primary?
							</label> -->
							<label>Email<sup><i class="fa fa-certificate text-danger"></i></sup></label>
							<input type="email" name="email[]" class="form-control" required=""  placeholder="Enter Email">
						</div>
						<div id="append_email"></div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12" >
					<button type="submit" class="btn btn-success">Save</button>
				</div>
			</div>
		</form>
	</div>
@endsection

@section('page-script')
	<script type="text/javascript">
		$(document).on('click','#add_mobile',function(){
			$('#append_mobile').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_mobile"><i class="fa fa-trash"></i></button>
					<input type="text" name="mobile[]" class="form-control"  placeholder="Enter Mobile number">
				</div>
			`)
		})

		$(document).on('click','.remove_mobile', function(){
			var r = confirm("Are You Sure?");
            if (r == true)
            {
				$(this).parent().remove();
			}
		});

		$(document).on('click','#add_whatsapp',function(){
			$('#append_whatsapp').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_whatsapp"><i class="fa fa-trash"></i></button>
					<input type="text" name="whatsapp_mobile[]" class="form-control"  placeholder="Enter Whatsapp number">
				</div>
			`)
		})

		$(document).on('click','.remove_whatsapp', function(){
			var r = confirm("Are You Sure?");
            if (r == true)
            {
				$(this).parent().remove();
			}
		});

		$(document).on('click','#add_email',function(){
			$('#append_email').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_email"><i class="fa fa-trash"></i></button>
					<input type="email" name="email[]" class="form-control"  placeholder="Enter Email">
				</div>
			`)
		})

		$(document).on('click','.remove_email', function(){
			var r = confirm("Are You Sure?");
            if (r == true)
            {
				$(this).parent().remove();
			}
		});
	</script>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.master')

@section('page-content')
	<div class="container">
		<form action="{{ route('employee.update',$employee->id) }}" method="post">
			@csrf
			{{ method_field('PUT') }}
			<div class="row">
				<div class="col-md-12">
					<h2>Employee Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label>Employee Name<sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="name" id="name" class="form-control" required="" placeholder="Enter Name" value="{{$employee->name}}">
						@error('name')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h2>Address Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label>Address 1<sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="address_line_1" id="address_line_1" class="form-control"  required="" placeholder="Enter Address 1" value="{{$employee->address_line_1}}">
						@error('address_line_1')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Address 2</label>
						<input type="text" name="address_line_2" id="address_line_2" class="form-control"  placeholder="Enter Address 2" value="{{$employee->address_line_2}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Location</label>
						<input type="text" name="location" id="location" class="form-control"  placeholder="Enter Address 2" value="{{$employee->location}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Zip/Pincode</label>
						<input type="text" name="zip_code" id="zip_code" class="form-control"  placeholder="Enter Zip/Pincode" value="{{$employee->zip_code}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Postal Area</label>
						<input type="text" name="postal_area" id="postal_area" class="form-control"  placeholder="Enter Postal Area" value="{{$employee->postal_area}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Taluka</label>
						<input type="text" name="taluka" id="taluka" class="form-control"  placeholder="Enter Taluka" value="{{$employee->taluka}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Suburb</label>
						<input type="text" name="suburb" id="suburb" class="form-control"  placeholder="Enter Taluka" value="{{$employee->suburb}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>East/West</label>
						<input type="text" name="direction" id="direction" class="form-control"  placeholder="Enter East/West" value="{{$employee->direction}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>City <sup><i class="fa fa-certificate text-danger"></i></sup></label>
						<input type="text" name="city" id="city" class="form-control" required="" placeholder="Enter East/West"value="{{$employee->city}}">
						@error('city')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>Distict</label>
						<input type="text" name="distict" id="distict" class="form-control"  placeholder="Enter Distict"value="{{$employee->distict}}">
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>State</label>
						<select class="form-control" name="state" id="state">
							<option value="">-- Select State --</option>
							@foreach($states as $state)
								<option value="{{$state->state_name}}" @if($state->state_name == 'MAHARASHTRA') selected @endif>{{$state->state_name}}</option>
							@endforeach
						</select>
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<label>County</label>
						<select class="form-control" name="country" id="country">
							<option value="">-- Select Country --</option>
							<option value="India" selected="">India</option>
							<option value="USA">USA</option>
							<option value="UK">UK</option>
							<option value="Shri Lanka">Shri Lanka</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h2>Contact Details</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_mobile" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Mobile Numbers </label>
						</div>
						@if(count($employee->mobile) > 0)
							@foreach($employee->mobile as $mobile)
								<div class="form-group">
									<button type="button" class="btn btn-default remove_mobile"><i class="fa fa-trash"></i></button>
									<!-- <label style="float:right;text-align:right"><input type="radio" name="primary_mobile[]" checked=""> Primary?</label> -->
									<input type="text" name="mobile[]" class="form-control"  placeholder="Enter Mobile number" value="{{$mobile->mobile}}">
									<input type="hidden" name="mobile_id[]" value="{{$mobile->id}}">
								</div>
							@endforeach
						@else
							<div class="form-group">
								<label>
									Mobile
								</label>
								<!-- <label style="float:right;text-align:right"><input type="radio" name="primary_mobile[]" checked=""> Primary?</label> -->
								<input type="text" name="mobile[]" class="form-control"  placeholder="Enter Mobile number">
								<input type="hidden" name="mobile_id[]">
							</div>
						@endif
						<div id="append_mobile"></div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_whatsapp" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Whatsapp Numbers</label>
						</div>
						@if(count($employee->whatsapp) > 0)
							@foreach($employee->whatsapp as $whatsapp)
								<div class="form-group">
									<button type="button" class="btn btn-default remove_whatsapp"><i class="fa fa-trash"></i></button>
									<input type="text" name="whatsapp_mobile[]" class="form-control"  placeholder="Enter Whatsapp number" value="{{$whatsapp->whatsapp_mobile}}">
									<input type="hidden" name="whatsapp_mobile_id[]" value="{{$whatsapp->id}}">
								</div>
							@endforeach
						@else
							<div class="form-group">
								<!-- <label style="float:right;text-align:right">
									<input type="radio" name="primary_whatsapp[]"  checked=""> Primary?
								</label> -->
								<label>Whatsapp Number</label>
								<input type="text" name="whatsapp_mobile[]" class="form-control"  placeholder="Enter Whatsapp number">
								<input type="hidden" name="whatsapp_mobile_id[]">
							</div>
						@endif
						<div id="append_whatsapp"></div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="col-md-12">
						<div>
							<button type="button" class="btn btn-default" id="add_email" style="float: right;text-align: right;"><i class="fa fa-plus"></i></button>
							<label>Email Addresses</label>
						</div>
						@if(count($employee->email) > 0)
							@foreach($employee->email as $email)
								<div class="form-group">
									<button type="button" class="btn btn-default remove_email"><i class="fa fa-trash"></i></button>
									<input type="email" name="email[]" class="form-control" required=""  placeholder="Enter Email" value="{{$email->email}}">
									<input type="hidden" name="email_id[]" value="{{$email->id}}">
								</div>
							@endforeach
						@else
							<div class="form-group">
								<!-- <label style="float:right;text-align:right">
										<input type="radio" name="primary_email[]" checked=""> Primary?
									</label> -->
								<label>Email<sup><i class="fa fa-certificate text-danger"></i></sup></label>
								<input type="email" name="email[]" class="form-control" required=""  placeholder="Enter Email">
								<input type="hidden" name="email_id[]">
							</div>
						@endif
						<div id="append_email"></div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12" >
					<button type="submit" class="btn btn-success">Save</button>
				</div>
			</div>
		</form>
	</div>
@endsection

@section('page-script')
	<script type="text/javascript">
		$(document).on('click','#add_mobile',function(){
			$('#append_mobile').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_mobile"><i class="fa fa-trash"></i></button>
					<input type="text" name="mobile[]" class="form-control"  placeholder="Enter Mobile number">
					<input type="hidden" name="mobile_id[]">
				</div>
			`)
		})

		$(document).on('click','.remove_mobile', function(){
			$(this).parent().remove();
		});

		$(document).on('click','#add_whatsapp',function(){
			$('#append_whatsapp').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_whatsapp"><i class="fa fa-trash"></i></button>
					<input type="text" name="whatsapp_mobile[]" class="form-control"  placeholder="Enter Whatsapp number">
					<input type="hidden" name="whatsapp_mobile_id[]">
				</div>
			`)
		})

		$(document).on('click','.remove_whatsapp', function(){
			$(this).parent().remove();
		});

		$(document).on('click','#add_email',function(){
			$('#append_email').append(`
				<div class="form-group">
					<button type="button" class="btn btn-default remove_email"><i class="fa fa-trash"></i></button>
					<input type="email" name="email[]" class="form-control"  placeholder="Enter Email">
					<input type="hidden" name="email_id[]">
				</div>
			`)
		})

		$(document).on('click','.remove_email', function(){
			$(this).parent().remove();
		});
	</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Target Assignment</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
</head>
<body>
	@yield('page-content')
	@yield('page-script')
</body>
</html>